2021-03-05 17:33:36,269 - test_order_manage.py[line:70] - ERROR: ---完成配送接口用例不通过，请检查问题---
